blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='index'),
    path('blog-details/', blog_details, name='blog-details'),
    path('blog-details/<int:pid>/', blog_details, name='blog-details'),
    path('category/<str:cat_name>/', blog, name='category'),
    path('tag/<str:tag_name>/', blog, name='tag'),
    path('author/<str:author_username>/', blog, name='author'),
    path('search/', blog_search, name='search'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', index, name='index'),
    path('shop/', shop, name='shop'),
    path('contact/', contact, name='contact'),
    path('shopping-cart/', shopping_cart, name='shopping-cart'),
    path('check-out/', check_out, name='check-out'),
    path('faq/', faq, name='faq'),
    path('product/', product, name='product'),
    path('about-us/', about_us, name='about-us'),
    path('services/', services, name='services'),
    path('newsletter/', newsletter, name='newsletter'),

    path('test/', test, name='test'),
]

website/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=127)
    message = models.TextField()
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["-created_date"]
        

class Newsletter(models.Model):
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email
    
    class Meta:
        ordering = ["-created_date"]

website/forms.py
from django.forms import ModelForm
from website.models import Contact, Newsletter

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

class NewsletterForm(ModelForm):
    class Meta:
        model = Newsletter
        fields = "__all__"
        

website/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from website.forms import ContactForm, NewsletterForm
# Create your views here.


def index(request):
    return render(request, 'website/index.html')

def shop(request):
    return render(request, 'website/shop.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if  form.is_valid():
            form.save()

    form = ContactForm()
    context = {'form':form}
    return render(request, 'website/contact.html', context)

def newsletter(request):
    if request.method == "POST":
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
    form = NewsletterForm()
    return HttpResponseRedirect('/')


def shopping_cart(request):
    return render(request, 'website/shopping-cart.html')

def check_out(request):
    return render(request, 'website/check-out.html')

def faq(request):
    return render(request, 'website/faq.html')


def product(request):
    return render(request, 'website/product.html')

def about_us(request):
    return render(request, 'website/about-us.html')

def services(request):
    return render(request, 'website/services.html')



def test(request):
    return HttpResponse('<h1>salam</h1>')

templates/website/about-us.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <a href="{% url 'website:index' %}"><i class="fa fa-home"></i> Home</a>
                        <span>About Us</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- About Section -->
    <section class="about-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <img src="{% static 'img/about.jpg' %}" alt="About Us" style="width:100%; border-radius:8px;">
                </div>
                <div class="col-lg-6">
                    <div class="about-text">
                        <h2>About Our Store</h2>
                        <p>
                            We started our business with the goal of providing high-quality products at fair prices.
                            Our mission is to create a simple, fast, and reliable online shopping experience for our
                            customers.
                        </p>
                        <p>
                            Our team is constantly updating products and improving services to ensure customer
                            satisfaction.
                            Your trust is our most valuable asset.
                        </p>
                        <ul>
                            <li><i class="fa fa-check"></i> Quality guaranteed</li>
                            <li><i class="fa fa-check"></i> Fast nationwide shipping</li>
                            <li><i class="fa fa-check"></i> 24/7 customer support</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Our Features -->
    <section class="benefit-items spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Free Shipping</h6>
                            <p>For orders over a certain amount</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-2.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>On-Time Delivery</h6>
                            <p>Fast and reliable delivery service</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Secure Payment</h6>
                            <p>100% secure online payment</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/website/check-out.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Section Begin -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text product-more">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <a href="./shop.html">Shop</a>
                        <span>Check Out</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section Begin -->

    <!-- Shopping Cart Section Begin -->
    <section class="checkout-section spad">
        <div class="container">
            <form action="#" class="checkout-form">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="checkout-content">
                            <a href="#" class="content-btn">Click Here To Login</a>
                        </div>
                        <h4>Biiling Details</h4>
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="fir">First Name<span>*</span></label>
                                <input type="text" id="fir">
                            </div>
                            <div class="col-lg-6">
                                <label for="last">Last Name<span>*</span></label>
                                <input type="text" id="last">
                            </div>
                            <div class="col-lg-12">
                                <label for="cun-name">Company Name</label>
                                <input type="text" id="cun-name">
                            </div>
                            <div class="col-lg-12">
                                <label for="cun">Country<span>*</span></label>
                                <input type="text" id="cun">
                            </div>
                            <div class="col-lg-12">
                                <label for="street">Street Address<span>*</span></label>
                                <input type="text" id="street" class="street-first">
                                <input type="text">
                            </div>
                            <div class="col-lg-12">
                                <label for="zip">Postcode / ZIP (optional)</label>
                                <input type="text" id="zip">
                            </div>
                            <div class="col-lg-12">
                                <label for="town">Town / City<span>*</span></label>
                                <input type="text" id="town">
                            </div>
                            <div class="col-lg-6">
                                <label for="email">Email Address<span>*</span></label>
                                <input type="text" id="email">
                            </div>
                            <div class="col-lg-6">
                                <label for="phone">Phone<span>*</span></label>
                                <input type="text" id="phone">
                            </div>
                            <div class="col-lg-12">
                                <div class="create-item">
                                    <label for="acc-create">
                                        Create an account?
                                        <input type="checkbox" id="acc-create">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="checkout-content">
                            <input type="text" placeholder="Enter Your Coupon Code">
                        </div>
                        <div class="place-order">
                            <h4>Your Order</h4>
                            <div class="order-total">
                                <ul class="order-table">
                                    <li>Product <span>Total</span></li>
                                    <li class="fw-normal">Combination x 1 <span>$60.00</span></li>
                                    <li class="fw-normal">Combination x 1 <span>$60.00</span></li>
                                    <li class="fw-normal">Combination x 1 <span>$120.00</span></li>
                                    <li class="fw-normal">Subtotal <span>$240.00</span></li>
                                    <li class="total-price">Total <span>$240.00</span></li>
                                </ul>
                                <div class="payment-check">
                                    <div class="pc-item">
                                        <label for="pc-check">
                                            Cheque Payment
                                            <input type="checkbox" id="pc-check">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="pc-item">
                                        <label for="pc-paypal">
                                            Paypal
                                            <input type="checkbox" id="pc-paypal">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                </div>
                                <div class="order-btn">
                                    <button type="submit" class="site-btn place-btn">Place Order</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <!-- Shopping Cart Section End -->

    <!-- Partner Logo Section Begin -->
    <div class="partner-logo">
        <div class="container">
            <div class="logo-carousel owl-carousel">
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-1.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-2.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-3.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-4.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-5.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Partner Logo Section End -->

  {% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Section Begin -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <a href="#"><i class="fa fa-home"></i> Home</a>
                        <span>Contact</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section Begin -->

    <!-- Map Section Begin -->
    <div class="map spad">
        <div class="container">
            <div class="map-inner">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48158.305462977965!2d-74.13283844036356!3d41.02757295168286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2e440473470d7%3A0xcaf503ca2ee57958!2sSaddle%20River%2C%20NJ%2007458%2C%20USA!5e0!3m2!1sen!2sbd!4v1575917275626!5m2!1sen!2sbd"
                    height="610" style="border:0" allowfullscreen="">
                </iframe>
                <div class="icon">
                    <i class="fa fa-map-marker"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- Map Section Begin -->

    <!-- Contact Section Begin -->
    <section class="contact-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="contact-title">
                        <h4>Contacts Us</h4>
                        <p>Contrary to popular belief, Lorem Ipsum is simply random text. It has roots in a piece of
                            classical Latin literature from 45 BC, maki years old.</p>
                    </div>
                    <div class="contact-widget">
                        <div class="cw-item">
                            <div class="ci-icon">
                                <i class="ti-location-pin"></i>
                            </div>
                            <div class="ci-text">
                                <span>Address:</span>
                                <p>60-49 Road 11378 New York</p>
                            </div>
                        </div>
                        <div class="cw-item">
                            <div class="ci-icon">
                                <i class="ti-mobile"></i>
                            </div>
                            <div class="ci-text">
                                <span>Phone:</span>
                                <p>+65 11.188.888</p>
                            </div>
                        </div>
                        <div class="cw-item">
                            <div class="ci-icon">
                                <i class="ti-email"></i>
                            </div>
                            <div class="ci-text">
                                <span>Email:</span>
                                <p>hellocolorlib@gmail.com</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 offset-lg-1">
                    <div class="contact-form">
                        <div class="leave-comment">
                            <h4>Leave A Comment</h4>
                            <p>Our staff will call back later and answer your questions.</p>
                            <form action="{% url 'website:contact' %}" class="comment-form" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <input type="text" placeholder="Your name" name="name">
                                    </div>
                                    <div class="col-lg-6">
                                        <input type="text" placeholder="Your email" name="email">
                                    </div>
                                    <div class="col-lg-12">
                                        <textarea placeholder="Your message" name="message"></textarea>
                                        <button type="submit" class="site-btn">Send message</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

    <!-- Partner Logo Section Begin -->
    <div class="partner-logo">
        <div class="container">
            <div class="logo-carousel owl-carousel">
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-1.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-2.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-3.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-4.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'img/logo-carousel/logo-5.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Partner Logo Section End -->
{% endblock %}

templates/website/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/website/recent-posts.html
{% load static %}
{% load website_tags %}
<section class="latest-blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>From The Blog</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in posts %}
            <div class="col-lg-4 col-md-6">
                <div class="single-latest-blog">
                    <img src="{{ post.image.url }}" alt="" id="website-recent">
                    <div class="latest-text">
                        <div class="tag-list">
                            <div class="tag-item">
                                <i class="fa fa-calendar-o"></i>
                                {{ post.published_date|date:'d M Y' }}
                            </div>
                            <div class="tag-item">
                                <i class="fa fa-comment-o"></i>
                                5
                            </div>
                        </div>
                        <a href="{% url 'blog:blog-details' pid=post.id %}">
                            <h4>{{ post.title }}</h4>
                        </a>
                        <p>{{ post.content|snippet }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="benefit-items">
            <div class="row">
                <div class="col-lg-4">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Free Shipping</h6>
                            <p>For all order over 99$</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-2.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Delivery On Time</h6>
                            <p>If good have prolems</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-benefit">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Secure Payment</h6>
                            <p>100% secure payment</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/website/services.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <a href="{% url 'website:index' %}"><i class="fa fa-home"></i> Home</a>
                        <span>Services</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Services Section -->
    <section class="services-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Our Services</h2>
                        <p>We provide high-quality services to ensure the best shopping experience.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="single-benefit text-center">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Fast Delivery</h6>
                            <p>Quick and reliable shipping nationwide.</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="single-benefit text-center">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-2.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Customer Support</h6>
                            <p>24/7 professional support for all customers.</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="single-benefit text-center">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Secure Payment</h6>
                            <p>Safe and encrypted online payments.</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="single-benefit text-center">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-2.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Product Quality</h6>
                            <p>Carefully selected high-quality products.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single-benefit text-center">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-1.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Easy Returns</h6>
                            <p>Simple and hassle-free return policy.</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="single-benefit text-center">
                        <div class="sb-icon">
                            <img src="{% static 'img/icon-2.png' %}" alt="">
                        </div>
                        <div class="sb-text">
                            <h6>Order Tracking</h6>
                            <p>Track your order in real time.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}