blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='index'),
    path('blog-details/', blog_details, name='blog-details'),
    path('blog-details/<int:pid>/', blog_details, name='blog-details'),
    path('category/<str:cat_name>/', blog, name='category'),
    path('tag/<str:tag_name>/', blog, name='tag'),
    path('author/<str:author_username>/', blog, name='author'),
    path('search/', blog_search, name='search'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', index, name='index'),
    path('shop/', shop, name='shop'),
    path('contact/', contact, name='contact'),
    path('shopping-cart/', shopping_cart, name='shopping-cart'),
    path('check-out/', check_out, name='check-out'),
    path('faq/', faq, name='faq'),
    path('product/', product, name='product'),
    path('about-us/', about_us, name='about-us'),
    path('services/', services, name='services'),
    path('newsletter/', newsletter, name='newsletter'),

    path('test/', test, name='test'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=127)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    tag = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=63)
    email = models.EmailField()
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.name

blog/forms.py
from blog.models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect
from blog.models import Post, Comment
from django.db.models import Q, F
from django.contrib import messages
from blog.forms import CommentForm

# Create your views here.

def blog(request, **kwargs):
    posts = Post.objects.filter(status=1).order_by('-published_date')
    
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])

    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])

    if kwargs.get('tag_name') != None:
        posts = posts.filter(tag__name__in=[kwargs['tag_name']])

    context = {
        'posts' : posts
    }

    return render(request, 'blog/blog-home.html', context)


def blog_details(request, **kwargs):
    pid = kwargs.get('pid')
    posts = Post.objects.filter(status=1)
    if not pid:
        raise Http404('Post Not Found')

    post = get_object_or_404(posts, pk=pid)
    next_post = posts.filter(published_date__gt=post.published_date).order_by('published_date').first()
    prev_post = posts.filter(published_date__lt=post.published_date).order_by('-published_date').first()

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your comment submited succesfully')
            return redirect('blog:blog-details', pid=pid)
        else:
            messages.add_message(request, messages.ERROR, 'Your comment didnt submited')
            return redirect('blog:blog-details', pid=pid)
        
    session_key = f'viewed_post_{post.id}'
    if not request.session.get(session_key, False):
        Post.objects.filter(pk=post.pk).update(counted_view=F('counted_view') + 1)
        request.session[session_key] = True
        post.refresh_from_db()

    comments = Comment.objects.filter(post=post.id, approved=True)
    form = CommentForm()

    context = {
        'post' : post,
        'next_post' : next_post,
        'prev_post' : prev_post,
        'form' : form,
        'comments' : comments,
    }

    return render(request, 'blog/blog-details.html', context)

def blog_search(request):
    posts = Post.objects.filter(status=1)

    if  (request.method == 'GET'):
        q = request.GET.get('s')
        
        posts = posts.filter(
            Q(title__icontains=q) |
            Q(content__icontains=q)
        )
        # posts = posts.filter(content__contains=request.GET.get('s'))

    context = {'posts' : posts}

    return render (request, 'blog/blog-home.html', context)

templates/blog/blog-category.html
{% load static %}
<div class="blog-catagory">
    <h4>Categories</h4>
    {% for cat, value in categories.items %}
    <ul>
        <a href="{% url 'blog:category' cat_name=cat.name %}" class="d-flex justify-content-between">
            <p>{{ cat.name }}</p>
            <p>{{ value }}</p>
        </a>
    </ul>
    {% endfor %}
</div>

templates/blog/blog-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Blog Details Section Begin -->
<section class="blog-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog-details-inner">
                    <div class="blog-detail-title">
                        <h2>{{ post.title }}</h2>
                        <!-- Category and Published Date -->
                        <p><a href="#" style="color:#ffc107;">{{ post.category.all|join:', ' }} </a> <span>{{ post.published_date|date:'d M Y' }}</span></p>
                        <!-- New Info: Author, View Count, Published Date -->
                        <div class="blog-meta">
                            <span><i class="fa fa-user"></i> Author:
                                <a href="{% url 'blog:author' author_username=post.author.username %}" style="color:#555;">{{ post.author.get_full_name }}</a></span>
                            <span><i class="fa fa-eye"></i> Views: {{ post.counted_view }}</span>
                        </div>
                    </div>

                    <div class="blog-large-pic">
                        <img src="{{ post.image.url }}" alt="" style="height: 510px; width: 272;">
                    </div>
                    <div class="blog-detail-desc">
                        <p>{{ post.content }}
                        </p>
                    </div>

                    <p>Sum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                        et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
                        nisi ut aliquip ex ea commodo consequat. Duis aute irure Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                        aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                        ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
                    <div class="tag-share">
                        <div class="details-tag">
                            <ul>
                                <li><i class="fa fa-tags"></i></li>
                                {% for tag in post.tag.all %}
                                <a href="{% url 'blog:tag' tag_name=tag.name %}"><li>{{ tag.name }}</li></a>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="blog-share">
                            <span>Share:</span>
                            <div class="social-links">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="blog-post">
                        <div class="row">
                            {% if prev_post and next_post %}
                            <div class="col-lg-5 col-md-6">
                                <a href="{% url 'blog:blog-details' pid=prev_post.id %}"
                                    class="prev-blog d-flex align-items-center">
                                    <div class="pb-pic me-3">
                                        <i class="ti-arrow-left"></i>
                                        <img src="{{ prev_post.image.url }}" alt="">
                                    </div>
                                    <div class="pb-text">
                                        <span>Previous Post:</span>
                                        <h5>{{ prev_post.title }}</h5>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-5 offset-lg-2 col-md-6">
                                <a href="{% url 'blog:blog-details' pid=next_post.id %}"
                                    class="next-blog d-flex align-items-center justify-content-end">
                                    <div class="nb-text text-end me-3">
                                        <span>Next Post:</span>
                                        <h5>{{ next_post.title }}</h5>
                                    </div>
                                    <div class="nb-pic">
                                        <img src="{{ next_post.image.url }}" alt="">
                                        <i class="ti-arrow-right"></i>
                                    </div>
                                </a>
                            </div>
                            {% elif prev_post %}
                            <div class="col-lg-12 col-md-12">
                                <a href="{% url 'blog:blog-details' pid=prev_post.id %}"
                                    class="prev-blog d-flex align-items-center justify-content-center">
                                    <div class="pb-pic me-3">
                                        <i class="ti-arrow-left"></i>
                                        <img src="{{ prev_post.image.url }}" alt="">
                                    </div>
                                    <div class="pb-text">
                                        <span>Previous Post:</span>
                                        <h5>{{ prev_post.title }}</h5>
                                    </div>
                                </a>
                            </div>
                            {% elif next_post %}
                            <div class="col-lg-12 col-md-12">
                                <a href="{% url 'blog:blog-details' pid=next_post.id %}"
                                    class="next-blog d-flex align-items-center justify-content-center">
                                    <div class="nb-text me-3 text-center">
                                        <span>Next Post:</span>
                                        <h5>{{ next_post.title }}</h5>
                                    </div>
                                    <div class="nb-pic">
                                        <img src="{{ next_post.image.url }}" alt="" >
                                        <i class="ti-arrow-right"></i>
                                    </div>
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    {% if not commnets %}
                        <p>There is no commnet, be the frist one</p>
                    {% endif %}
                    {% for comment in comments %}
                    <div class="posted-by">
                        <div class="pb-pic">
                            <img src="{% static 'img/blog/comment.png' %}" alt="" style="height: 91px; width: 89px;">
                        </div>
                        
                        <div class="pb-text">
                            <a href="#">
                                <h5>{{ comment.name }}</h5>
                            </a>
                            <p>{{ comment.message }}</p>
                        </div>
                        
                    </div>
                    {% endfor %}
                    <div class="leave-comment">
                        <h4>Leave A Comment</h4>
                        <form action="{% url 'blog:blog-details' pid=post.id %}" class="comment-form" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="post" value="{{ post.id }}">
                            <div class="row">
                                <div class="col-lg-6">
                                    <input type="text" placeholder="Name" name="name">
                                </div>
                                <div class="col-lg-6">
                                    <input type="text" placeholder="Email" name="email">
                                </div>
                                <div class="col-lg-12">
                                    <textarea placeholder="Messages" name="message"></textarea>
                                    <button type="submit" class="site-btn">Send message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Section End -->

<!-- Partner Logo Section Begin -->
<div class="partner-logo">
    <div class="container">
        <div class="logo-carousel owl-carousel">
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-1.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-2.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-3.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-4.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-5.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Partner Logo Section End -->
{% endblock %}

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}

<!-- Breadcrumb Section Begin -->
<div class="breacrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <a href="{% url 'website:index' %}"><i class="fa fa-home"></i> Home</a>
                    <span>Blog</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section Begin -->

<!-- Blog Section Begin -->
<section class="blog-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1">
                <div class="blog-sidebar">
                    {% include 'blog/blog-search.html' %}

                    {% categories %}

                    {% recent_posts %}

                    {% blog_tags %}

                </div>
            </div>
            <div class="col-lg-9 order-1 order-lg-2">
                <div class="row">
                    {% for post in posts %}
                    <div class="col-lg-6 col-sm-6">
                        <div class="blog-item">
                            <div class="single-latest-blog ">
                                <img src="{{ post.image.url }}" alt="" >
                            </div>
                            <div class="bi-text">
                                <a href="{% url 'blog:blog-details' pid=post.id %}">
                                    <h4>{{ post.title }}</h4>
                                </a>
                                <p>
                                    {% for cat in post.category.all %}
                                    <a href="{% url 'blog:category' cat_name=cat.name %}"
                                        style="color:#ffc107;">{{cat.name }}</a>{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                    <span>- {{ post.published_date|naturaltime }}</span>
                                    <span>- {{ post.counted_view|intcomma }} views</span>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-lg-12">
                        <div class="loading-more">
                            <i class="icon_loading"></i>
                            <a href="#">
                                Loading More
                            </a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Section End -->

<!-- Partner Logo Section Begin -->
<div class="partner-logo">
    <div class="container">
        <div class="logo-carousel owl-carousel">
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-1.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-2.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-3.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-4.png' %}" alt="">
                </div>
            </div>
            <div class="logo-item">
                <div class="tablecell-inner">
                    <img src="{% static 'img/logo-carousel/logo-5.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Partner Logo Section End -->
{% endblock %}

templates/blog/blog-recent.html
{% load static %}
{% load humanize %}
{% load blog_tags %}

<div class="recent-post">
    <h4>Recent Post</h4>
    {% for post in posts %}
    <div class="recent-blog">
        <a href="{% url 'blog:blog-details' pid=post.id %}" class="rb-item">
            <div class="rb-pic">
                <img src="{{ post.image.url }}" alt="">
            </div>
            <div class="rb-text">
                <h6>{{ post.title }}</h6>

                {% for cat in post.category.all %}
                <p>
                    {{ cat.name }}{% if not forloop.last %}, {% endif %}
                </p>
                {% endfor %}

                <p class="meta">
                    <span>{{ post.published_date|naturaltime }}</span>
                </p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

templates/blog/blog-search.html
<div class="search-form">
    <h4>Search</h4>
    <form action="{% url 'blog:search' %}" method="get">
        <input type="text" placeholder="Search . . .  " name="s">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-tag.html
<div class="blog-tags">
    <h4>Product Tags</h4>
    <div class="tag-item">
        {% for tag in tags %}
        <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
        {% endfor %}
    </div>
</div>